In [2]:
import numpy as np

In [2]:
listem=[3,4,56,6,9]


In [3]:
np.array(listem)

array([ 3,  4, 56,  6,  9])

In [5]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [7]:
np.arange(0,10,4)

array([0, 4, 8])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [11]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
np.linspace(0,100,40)

array([  0.        ,   2.56410256,   5.12820513,   7.69230769,
        10.25641026,  12.82051282,  15.38461538,  17.94871795,
        20.51282051,  23.07692308,  25.64102564,  28.20512821,
        30.76923077,  33.33333333,  35.8974359 ,  38.46153846,
        41.02564103,  43.58974359,  46.15384615,  48.71794872,
        51.28205128,  53.84615385,  56.41025641,  58.97435897,
        61.53846154,  64.1025641 ,  66.66666667,  69.23076923,
        71.79487179,  74.35897436,  76.92307692,  79.48717949,
        82.05128205,  84.61538462,  87.17948718,  89.74358974,
        92.30769231,  94.87179487,  97.43589744, 100.        ])

In [13]:
np.linspace(1,10,7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## random


In [16]:
np.random.rand(7)

array([0.53535675, 0.39340626, 0.64589068, 0.03114284, 0.80487696,
       0.55303786, 0.28119394])

In [17]:
np.random.randn(4)

array([-0.5292302 , -0.56080355, -0.37771032, -1.03743217])

In [18]:
np.random.randn(4,2)

array([[-0.06973369, -0.73401784],
       [ 0.90491235, -1.58677319],
       [ 0.00716293,  0.99825659],
       [ 0.49012676, -0.32744103]])

In [19]:
np.random.randint(0,100,20)

array([72, 80, 70, 54, 94, 53, 53, 14, 65, 68, 91, 44, 24, 95, 46, 65, 14,
        9, 73,  4])

In [32]:
np.random.random(5)

array([0.65943142, 0.57010865, 0.79780097, 0.5792489 , 0.06369311])

In [33]:
benimnumpydizim=np.arange(10)

In [34]:
benimnumpydizim

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
benimrandomdizim=np.random.randint(1,100,20)

In [49]:
benimrandomdizim

array([13, 45, 49, 79, 39, 63, 95, 83, 71, 70, 45, 40, 26, 42,  1, 55, 93,
       20, 56, 83])

# methodlar

In [43]:
benimnumpydizim.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [44]:
benimnumpydizim.shape

(10,)

In [50]:
benimrandomdizim.max()

95

In [51]:
benimrandomdizim.argmax()

6

rashapedizim=benimnumpydizim.reshape(2,5)

In [52]:
reshapesizim

NameError: name 'reshapesizim' is not defined

In [53]:
reshapedizim=benimnumpydizim.reshape(2,5)

In [54]:
reshapedizim.shape

(2, 5)

# operasyonlar

In [55]:
ornekdizim=np.arange(1,31)

In [56]:
ornekdizim

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [57]:
ornekdizimkopya=ornekdizim.copy()

In [58]:
ornekdizimkopya

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [59]:
ornekSlicing=ornekdizimkopya[3:8]

In [60]:
ornekSlicing

array([4, 5, 6, 7, 8])

In [61]:
ornekSlicing[:]=888

In [62]:
ornekSlicing

array([888, 888, 888, 888, 888])

In [63]:
ornekdizimkopya

array([  1,   2,   3, 888, 888, 888, 888, 888,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30])

In [64]:
ornekdizim

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

# matrix

In [67]:
a=np.random.randint(1,10,3)
b=np.random.randint(1,10,3)
c=np.random.randint(1,10,3)

In [69]:
a

array([6, 5, 8])

In [70]:
b

array([6, 3, 2])

In [71]:
c

array([2, 2, 3])

In [72]:
listem=[a,b,c]

In [73]:
listem

[array([6, 5, 8]), array([6, 3, 2]), array([2, 2, 3])]

In [74]:
matrixdizim=np.array(listem)

In [75]:
matrixdizim

array([[6, 5, 8],
       [6, 3, 2],
       [2, 2, 3]])

In [77]:
matrixdizim[1,2]

2

In [79]:
matrixdizim[1,:2]

array([6, 3])

In [80]:
matrixdizim[1:,1]

array([3, 2])

In [81]:
matrixdizim[1:,2:]

array([[2],
       [3]])

In [86]:
matrixdizim[[2,1]]

array([[2, 2, 3],
       [6, 3, 2]])

# operasyonlar

In [87]:
yenidizi=np.random.randint(1,50,10)

In [88]:
yenidizi

array([19, 35, 40, 35,  2, 11, 47, 21, 40, 49])

In [89]:
ele=yenidizi>25

In [90]:
ele

array([False,  True,  True,  True, False, False,  True, False,  True,
        True])

In [92]:
yenidizi[ele]

array([35, 40, 35, 47, 40, 49])

In [93]:
yenidizi[yenidizi<10]

array([2])

In [94]:
sondizi=np.arange(1,20)

In [95]:
sondizi

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [96]:
sondizi*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [97]:
sondizi*sondizi

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [98]:
# karekök

In [99]:
np.sqrt(sondizi)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [100]:
np.square(sondizi)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [63]:
asd=np.random.randint(10,100,15).reshape(5,3)

In [64]:
asd

array([[48, 43, 27],
       [79, 15, 36],
       [76, 44, 66],
       [94, 44, 75],
       [71, 99, 12]])